name: flutter_tools
description: Tools for building Flutter applications
homepage: https://flutter.dev
author: Flutter Authors <flutter-dev@googlegroups.com>

environment:
  # The pub client defaults to an <2.0.0 sdk constraint which we need to explicitly overwrite.
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  # To update these, use "flutter update-packages --force-upgrade".
  archive: 2.0.13
  args: 1.6.0
  dds: 1.4.0
  dwds: 6.0.0
  completion: 0.2.2
  coverage: 0.14.1
  crypto: 2.1.5
  file: 6.0.0-nullsafety.2
  flutter_template_images: 1.0.1
  http: 0.12.2
  intl: 0.16.1
  meta: 1.3.0-nullsafety.3
  multicast_dns: 0.2.2
  mustache_template: 1.0.0+1
  package_config: 1.9.3
  process: 4.0.0-nullsafety.2
  fake_async: 1.2.0-nullsafety.1
  stack_trace: 1.10.0-nullsafety.2
  usage: 3.4.2
  webdriver: 2.1.2
  webkit_inspection_protocol: 0.7.3
  xml: 4.5.1
  yaml: 2.2.1
  native_stack_traces: 0.3.7
  shelf: 0.7.5
  vm_snapshot_analysis: 0.5.5
  uuid: 2.2.2
  web_socket_channel: 1.1.0
  stream_channel: 2.1.0-nullsafety.1
  shelf_web_socket: 0.2.3
  shelf_static: 0.2.8
  shelf_packages_handler: 2.0.0
  pub_semver: 1.4.4
  pool: 1.5.0-nullsafety.1
  path: 1.8.0-nullsafety.1
  mime: 0.9.7
  logging: 0.11.4
  http_multi_server: 2.2.0
  devtools_server: 0.8.0+3
  convert: 2.1.1
  async: 2.5.0-nullsafety.1

  # We depend on very specific internal implementation details of the
  # 'test' package, which change between versions, so when upgrading
  # this, make sure the tests are still running correctly.
  test_api: 0.2.19-nullsafety.2
  test_core: 0.3.12-nullsafety.5

  vm_service: 4.2.0

dev_dependencies:
  collection: 1.15.0-nullsafety.3
  mockito: 4.1.1
  file_testing: 2.1.0
  test: 1.16.0-nullsafety.5
  pubspec_parse: 0.1.5


dartdoc:
  # Exclude this package from the hosted API docs.
  nodoc: true

# PUBSPEC CHECKSUM: 9d86
