name: flutter_driver
description: Integration and performance test API for Flutter applications
homepage: http://flutter.dev
author: Flutter Authors <flutter-dev@googlegroups.com>

environment:
  # The pub client defaults to an <2.0.0 sdk constraint which we need to explicitly overwrite.
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  file: 5.1.0
  meta: 1.1.8
  path: 1.7.0
  webdriver: 2.1.2
  vm_service: 4.0.4
  flutter:
    sdk: flutter
  fuchsia_remote_debug_protocol:
    sdk: flutter

dev_dependencies:
  mockito: 4.1.1
  quiver: 2.1.3

# PUBSPEC CHECKSUM: 0c74
